package pojos;
// Generated 28-nov-2016 13:35:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Agencia generated by hbm2java
 */
public class Agencia  implements java.io.Serializable {


     private Integer idAgencia;
     private String nombre;
     private String telefono1;
     private String telefono2;
     private String fax;
     private String direccion;
     private String zona;
     private Set vendedors = new HashSet(0);
     private Set inmuebles = new HashSet(0);

    public Agencia() {
    }

	
    public Agencia(String nombre, String telefono1, String direccion, String zona) {
        this.nombre = nombre;
        this.telefono1 = telefono1;
        this.direccion = direccion;
        this.zona = zona;
    }
    public Agencia(String nombre, String telefono1, String telefono2, String fax, String direccion, String zona, Set vendedors, Set inmuebles) {
       this.nombre = nombre;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.fax = fax;
       this.direccion = direccion;
       this.zona = zona;
       this.vendedors = vendedors;
       this.inmuebles = inmuebles;
    }
   
    public Integer getIdAgencia() {
        return this.idAgencia;
    }
    
    public void setIdAgencia(Integer idAgencia) {
        this.idAgencia = idAgencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }
    public Set getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set vendedors) {
        this.vendedors = vendedors;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }




}


