/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Manuel
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(true);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitular = new javax.swing.JPanel();
        btnTitVentas = new javax.swing.JButton();
        lblNombreAgencia = new javax.swing.JLabel();
        btnTitInmuebles = new javax.swing.JButton();
        btnTitVendedores = new javax.swing.JButton();
        panelTitVendedores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTitVendedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTitVenCodAgencia = new javax.swing.JLabel();
        lblTitVenNombreAgencia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTitVenApellidos = new javax.swing.JTextField();
        txtTitVenNombre = new javax.swing.JTextField();
        txtTitVenDni = new javax.swing.JTextField();
        txtTitVenTelefono = new javax.swing.JTextField();
        txtTiVentCorreo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnTitVenNuevo = new javax.swing.JButton();
        btnTitVenGuardar = new javax.swing.JButton();
        btnTitVenModificar = new javax.swing.JButton();
        btnTitVenSalir = new javax.swing.JButton();
        btnTitVenEliminar = new javax.swing.JButton();
        panelTitInmuebles = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTitInmCodAgencia = new javax.swing.JLabel();
        lblTitInmNombreAgencia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTitInmueble = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTitInmPropietario = new javax.swing.JTextField();
        txtTitInmDireccion = new javax.swing.JTextField();
        txtTitInmSuperficie = new javax.swing.JTextField();
        txtTitInmLicencia = new javax.swing.JTextField();
        txtTitInmNumHab = new javax.swing.JTextField();
        txtTitInmNumBaños = new javax.swing.JTextField();
        txtTitInmTipoGas = new javax.swing.JTextField();
        txtTitInmUbicacion = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnTitInmNuevoLocal = new javax.swing.JButton();
        btnTitInmGuardar = new javax.swing.JButton();
        btnTitInmModificar = new javax.swing.JButton();
        btnTitInmSalir = new javax.swing.JButton();
        btnTitInmEliminar = new javax.swing.JButton();
        btnTitInmNuevoPiso = new javax.swing.JButton();
        panelTitVentas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTitVentas = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lblTitVentaCodAgencia = new javax.swing.JLabel();
        lblTitVentaNombreAgencia = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtTitVentaDni = new javax.swing.JTextField();
        txtTitVentaNombre = new javax.swing.JTextField();
        txtTitVentaApellidos = new javax.swing.JTextField();
        txtTitVentaTelefono = new javax.swing.JTextField();
        txtTitVentaSeñal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnTitVentaModificar = new javax.swing.JButton();
        btnTitVentaEliminar = new javax.swing.JButton();
        btnTitVentaSalir = new javax.swing.JButton();
        panelVendedor = new javax.swing.JPanel();
        btnVendClientes = new javax.swing.JButton();
        lblNombreAgencia1 = new javax.swing.JLabel();
        btnVendNuevaVenta = new javax.swing.JButton();
        panelVendNuevaVenta = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaVendVentas = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        lblVendVentaCodAgencia = new javax.swing.JLabel();
        lblVendVentaNombreAgencia = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtVendVentaDni = new javax.swing.JTextField();
        txtVendVentaNombre = new javax.swing.JTextField();
        txtVendVentaApellidos = new javax.swing.JTextField();
        txtVendVentaTelefono = new javax.swing.JTextField();
        txtVendVentaSeñal = new javax.swing.JTextField();
        btnVendBuscarCliente = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnVendVentaModificar = new javax.swing.JButton();
        btnVendVentaEliminar = new javax.swing.JButton();
        btnVendVentaSalir = new javax.swing.JButton();
        btnVendVentaGuardar = new javax.swing.JButton();
        btnVendVentaNuevo = new javax.swing.JButton();
        panelVendCliente = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaVendCliente = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        lblVendClienteCodAgencia = new javax.swing.JLabel();
        lblVendClienteNombreAgencia = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtVendClienteDni = new javax.swing.JTextField();
        txtVendClienteNombre = new javax.swing.JTextField();
        txtVendClienteApellidos = new javax.swing.JTextField();
        txtVendClienteTelefono = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btnVendClienteModificar = new javax.swing.JButton();
        btnVendClienteEliminar = new javax.swing.JButton();
        btnVendClienteSalir = new javax.swing.JButton();
        btnVendClienteGuardar = new javax.swing.JButton();
        btnVendClienteNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTitVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventasNor.png"))); // NOI18N
        btnTitVentas.setBorder(null);
        btnTitVentas.setBorderPainted(false);
        btnTitVentas.setContentAreaFilled(false);
        btnTitVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTitVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTitVentas.setIconTextGap(-3);
        btnTitVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventasPre.png"))); // NOI18N
        btnTitVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventasRol.png"))); // NOI18N
        btnTitVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitVentasActionPerformed(evt);
            }
        });

        lblNombreAgencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNombreAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreAgencia.setText("NOMBRE DE LA INMOBILIARIA");

        btnTitInmuebles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InmueblesNor.png"))); // NOI18N
        btnTitInmuebles.setBorder(null);
        btnTitInmuebles.setBorderPainted(false);
        btnTitInmuebles.setContentAreaFilled(false);
        btnTitInmuebles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTitInmuebles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTitInmuebles.setIconTextGap(-3);
        btnTitInmuebles.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InmueblesPre.png"))); // NOI18N
        btnTitInmuebles.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/InmueblesRol.png"))); // NOI18N
        btnTitInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitInmueblesActionPerformed(evt);
            }
        });

        btnTitVendedores.setBackground(new java.awt.Color(0, 0, 0));
        btnTitVendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vendedorNor.png"))); // NOI18N
        btnTitVendedores.setBorder(null);
        btnTitVendedores.setBorderPainted(false);
        btnTitVendedores.setContentAreaFilled(false);
        btnTitVendedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTitVendedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTitVendedores.setIconTextGap(-3);
        btnTitVendedores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vendedorPre.png"))); // NOI18N
        btnTitVendedores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vendedorRol.png"))); // NOI18N
        btnTitVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitVendedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTitularLayout = new javax.swing.GroupLayout(panelTitular);
        panelTitular.setLayout(panelTitularLayout);
        panelTitularLayout.setHorizontalGroup(
            panelTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitularLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTitVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnTitInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btnTitVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        panelTitularLayout.setVerticalGroup(
            panelTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitularLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(panelTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTitVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitInmuebles, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        tablaTitVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTitVendedor);

        jLabel1.setText("Código Agencia: ");

        lblTitVenCodAgencia.setText("codigo");

        lblTitVenNombreAgencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitVenNombreAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitVenNombreAgencia.setText("NOMBRE DE LA INMOBILIARIA");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Vendedor"));

        jLabel5.setText("Apellidos:");

        jLabel4.setText("Nombre:");

        jLabel3.setText("DNI:");

        jLabel6.setText("Teléfono:");

        jLabel7.setText("Correo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitVenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTiVentCorreo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitVenApellidos)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTitVenDni, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitVenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitVenDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTitVenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTitVenApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTitVenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTiVentCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTitVenNuevo.setText("Nuevo");
        jPanel3.add(btnTitVenNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        btnTitVenGuardar.setText("Guardar");
        jPanel3.add(btnTitVenGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        btnTitVenModificar.setText("Modificar");
        jPanel3.add(btnTitVenModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 140, -1));

        btnTitVenSalir.setText("Salir");
        btnTitVenSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitVenSalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnTitVenSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, -1));

        btnTitVenEliminar.setText("Eliminar");
        jPanel3.add(btnTitVenEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 140, -1));

        javax.swing.GroupLayout panelTitVendedoresLayout = new javax.swing.GroupLayout(panelTitVendedores);
        panelTitVendedores.setLayout(panelTitVendedoresLayout);
        panelTitVendedoresLayout.setHorizontalGroup(
            panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTitVendedoresLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitVenNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTitVendedoresLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTitVendedoresLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(6, 6, 6)
                                    .addComponent(lblTitVenCodAgencia))
                                .addGroup(panelTitVendedoresLayout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)))
        );
        panelTitVendedoresLayout.setVerticalGroup(
            panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTitVendedoresLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lblTitVenCodAgencia))
                    .addGap(6, 6, 6)
                    .addComponent(lblTitVenNombreAgencia)
                    .addGap(60, 60, 60)
                    .addGroup(panelTitVendedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelTitVendedoresLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(38, 38, 38)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        jLabel2.setText("Código Agencia: ");

        lblTitInmCodAgencia.setText("codigo");

        lblTitInmNombreAgencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitInmNombreAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitInmNombreAgencia.setText("NOMBRE DE LA INMOBILIARIA");

        tablaTitInmueble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaTitInmueble);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del Inmueble"));

        jLabel8.setText("Direccion:");

        jLabel9.setText("Propietario:");

        jLabel10.setText("Superficie");

        jLabel11.setText("Num. Habitaciones:");

        jLabel12.setText("Num. Baños:");

        jLabel13.setText("Tipo de Gas:");

        jLabel16.setText("Licencia:");

        jLabel15.setText("Ubicación:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitInmLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitInmSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitInmDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitInmPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitInmUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitInmTipoGas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitInmNumBaños, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitInmNumHab, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTitInmDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTitInmNumHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTitInmPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtTitInmNumBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTitInmSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTitInmTipoGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTitInmLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTitInmUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTitInmNuevoLocal.setText("Nuevo Local");
        jPanel4.add(btnTitInmNuevoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, -1));

        btnTitInmGuardar.setText("Guardar");
        jPanel4.add(btnTitInmGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, -1));

        btnTitInmModificar.setText("Modificar");
        btnTitInmModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitInmModificarActionPerformed(evt);
            }
        });
        jPanel4.add(btnTitInmModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, -1));

        btnTitInmSalir.setText("Salir");
        btnTitInmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitInmSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnTitInmSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, -1));

        btnTitInmEliminar.setText("Eliminar");
        jPanel4.add(btnTitInmEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, -1));

        btnTitInmNuevoPiso.setText("Nuevo Piso");
        jPanel4.add(btnTitInmNuevoPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, -1));

        javax.swing.GroupLayout panelTitInmueblesLayout = new javax.swing.GroupLayout(panelTitInmuebles);
        panelTitInmuebles.setLayout(panelTitInmueblesLayout);
        panelTitInmueblesLayout.setHorizontalGroup(
            panelTitInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitInmNombreAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTitInmueblesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(lblTitInmCodAgencia)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelTitInmueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(panelTitInmueblesLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTitInmueblesLayout.setVerticalGroup(
            panelTitInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitInmueblesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblTitInmCodAgencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitInmNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelTitInmueblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablaTitVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaTitVentas);

        jLabel14.setText("Código Agencia: ");

        lblTitVentaCodAgencia.setText("codigo");

        lblTitVentaNombreAgencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitVentaNombreAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitVentaNombreAgencia.setText("NOMBRE DE LA INMOBILIARIA");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Venta"));

        jLabel17.setText("DNI Cliente:");

        jLabel18.setText("Nombre:");

        jLabel19.setText("Apellidos:");

        jLabel20.setText("Telefono:");

        jLabel21.setText("Señal:");

        jLabel22.setText("Fecha:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitVentaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitVentaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitVentaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitVentaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitVentaSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTitVentaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtTitVentaSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTitVentaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTitVentaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTitVentaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTitVentaModificar.setText("Modificar");

        btnTitVentaEliminar.setText("Eliminar");

        btnTitVentaSalir.setText("Salir");
        btnTitVentaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitVentaSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTitVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitVentaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTitVentaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTitVentaModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTitVentaEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTitVentaSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelTitVentasLayout = new javax.swing.GroupLayout(panelTitVentas);
        panelTitVentas.setLayout(panelTitVentasLayout);
        panelTitVentasLayout.setHorizontalGroup(
            panelTitVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitVentaNombreAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
            .addGroup(panelTitVentasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(lblTitVentaCodAgencia)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelTitVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(panelTitVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitVentasLayout.setVerticalGroup(
            panelTitVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTitVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lblTitVentaCodAgencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitVentaNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTitVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnVendClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientesNor.png"))); // NOI18N
        btnVendClientes.setBorder(null);
        btnVendClientes.setBorderPainted(false);
        btnVendClientes.setContentAreaFilled(false);
        btnVendClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendClientes.setIconTextGap(-3);
        btnVendClientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientesPres.png"))); // NOI18N
        btnVendClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientesRol.png"))); // NOI18N
        btnVendClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendClientesActionPerformed(evt);
            }
        });

        lblNombreAgencia1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblNombreAgencia1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreAgencia1.setText("NOMBRE DE LA INMOBILIARIA");

        btnVendNuevaVenta.setBackground(new java.awt.Color(0, 0, 0));
        btnVendNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventasNor.png"))); // NOI18N
        btnVendNuevaVenta.setBorder(null);
        btnVendNuevaVenta.setBorderPainted(false);
        btnVendNuevaVenta.setContentAreaFilled(false);
        btnVendNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVendNuevaVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendNuevaVenta.setIconTextGap(-3);
        btnVendNuevaVenta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventasPre.png"))); // NOI18N
        btnVendNuevaVenta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventasRol.png"))); // NOI18N
        btnVendNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendNuevaVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVendedorLayout = new javax.swing.GroupLayout(panelVendedor);
        panelVendedor.setLayout(panelVendedorLayout);
        panelVendedorLayout.setHorizontalGroup(
            panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombreAgencia1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVendNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(btnVendClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
        );
        panelVendedorLayout.setVerticalGroup(
            panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendedorLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblNombreAgencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(panelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        tablaVendVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaVendVentas);

        jLabel30.setText("Código Agencia: ");

        lblVendVentaCodAgencia.setText("codigo");

        lblVendVentaNombreAgencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblVendVentaNombreAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendVentaNombreAgencia.setText("NOMBRE DE LA INMOBILIARIA");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de Venta"));

        jLabel31.setText("DNI Cliente:");

        jLabel32.setText("Nombre:");

        jLabel33.setText("Apellidos:");

        jLabel34.setText("Telefono:");

        jLabel35.setText("Señal:");

        jLabel36.setText("Fecha:");

        btnVendBuscarCliente.setText("Buscar Cliente");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVendVentaApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txtVendVentaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txtVendVentaDni, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(btnVendBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel35))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVendVentaTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtVendVentaSeñal))
                .addGap(41, 41, 41))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtVendVentaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtVendVentaSeñal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtVendVentaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtVendVentaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtVendVentaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVendVentaModificar.setText("Modificar");

        btnVendVentaEliminar.setText("Eliminar");

        btnVendVentaSalir.setText("Salir");
        btnVendVentaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendVentaSalirActionPerformed(evt);
            }
        });

        btnVendVentaGuardar.setText("Guardar");

        btnVendVentaNuevo.setText("Nuevo");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendVentaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendVentaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendVentaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendVentaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendVentaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVendVentaNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendVentaGuardar)
                .addGap(8, 8, 8)
                .addComponent(btnVendVentaModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendVentaEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVendVentaSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelVendNuevaVentaLayout = new javax.swing.GroupLayout(panelVendNuevaVenta);
        panelVendNuevaVenta.setLayout(panelVendNuevaVentaLayout);
        panelVendNuevaVentaLayout.setHorizontalGroup(
            panelVendNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVendVentaNombreAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
            .addGroup(panelVendNuevaVentaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel30)
                .addGap(6, 6, 6)
                .addComponent(lblVendVentaCodAgencia)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelVendNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(panelVendNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVendNuevaVentaLayout.setVerticalGroup(
            panelVendNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVendNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(lblVendVentaCodAgencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVendVentaNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelVendNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaVendCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaVendCliente);

        jLabel37.setText("Código Agencia: ");

        lblVendClienteCodAgencia.setText("codigo");

        lblVendClienteNombreAgencia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblVendClienteNombreAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVendClienteNombreAgencia.setText("NOMBRE DE LA INMOBILIARIA");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del Cliente"));

        jLabel38.setText("DNI Cliente:");

        jLabel39.setText("Nombre:");

        jLabel40.setText("Apellidos:");

        jLabel41.setText("Telefono:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVendClienteDni, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txtVendClienteNombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVendClienteTelefono)
                    .addComponent(txtVendClienteApellidos))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtVendClienteDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(txtVendClienteApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtVendClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(txtVendClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVendClienteModificar.setText("Modificar");

        btnVendClienteEliminar.setText("Eliminar");

        btnVendClienteSalir.setText("Salir");
        btnVendClienteSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendClienteSalirActionPerformed(evt);
            }
        });

        btnVendClienteGuardar.setText("Guardar");

        btnVendClienteNuevo.setText("Nuevo");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVendClienteModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendClienteSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendClienteNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVendClienteGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVendClienteNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendClienteGuardar)
                .addGap(8, 8, 8)
                .addComponent(btnVendClienteModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVendClienteEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnVendClienteSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelVendClienteLayout = new javax.swing.GroupLayout(panelVendCliente);
        panelVendCliente.setLayout(panelVendClienteLayout);
        panelVendClienteLayout.setHorizontalGroup(
            panelVendClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVendClienteNombreAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(panelVendClienteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel37)
                .addGap(6, 6, 6)
                .addComponent(lblVendClienteCodAgencia)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelVendClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVendClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(panelVendClienteLayout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelVendClienteLayout.setVerticalGroup(
            panelVendClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVendClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVendClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(lblVendClienteCodAgencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVendClienteNombreAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelVendClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTitVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTitInmuebles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTitVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVendNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVendCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(panelTitVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTitInmuebles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(panelTitVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(panelVendNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelVendCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(23, 23, 23)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTitVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitVentasActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(true);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnTitVentasActionPerformed

    private void btnTitVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitVendedoresActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(true);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);       
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnTitVendedoresActionPerformed

    private void btnTitInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitInmueblesActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(true);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnTitInmueblesActionPerformed

    private void btnTitInmModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitInmModificarActionPerformed
        
    }//GEN-LAST:event_btnTitInmModificarActionPerformed

    private void btnTitVenSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitVenSalirActionPerformed
        this.panelTitular.setVisible(true);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnTitVenSalirActionPerformed

    private void btnTitInmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitInmSalirActionPerformed
        this.panelTitular.setVisible(true);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnTitInmSalirActionPerformed

    private void btnTitVentaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitVentaSalirActionPerformed
        this.panelTitular.setVisible(true);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnTitVentaSalirActionPerformed

    private void btnVendVentaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendVentaSalirActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(true);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnVendVentaSalirActionPerformed

    private void btnVendNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendNuevaVentaActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(true);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnVendNuevaVentaActionPerformed

    private void btnVendClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendClientesActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(false);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(true);
    }//GEN-LAST:event_btnVendClientesActionPerformed

    private void btnVendClienteSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendClienteSalirActionPerformed
        this.panelTitular.setVisible(false);
        this.panelTitVendedores.setVisible(false);
        this.panelTitInmuebles.setVisible(false);
        this.panelTitVentas.setVisible(false);
        
        this.panelVendedor.setVisible(true);
        this.panelVendNuevaVenta.setVisible(false);
        this.panelVendCliente.setVisible(false);
    }//GEN-LAST:event_btnVendClienteSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTitInmEliminar;
    private javax.swing.JButton btnTitInmGuardar;
    private javax.swing.JButton btnTitInmModificar;
    private javax.swing.JButton btnTitInmNuevoLocal;
    private javax.swing.JButton btnTitInmNuevoPiso;
    private javax.swing.JButton btnTitInmSalir;
    private javax.swing.JButton btnTitInmuebles;
    private javax.swing.JButton btnTitVenEliminar;
    private javax.swing.JButton btnTitVenGuardar;
    private javax.swing.JButton btnTitVenModificar;
    private javax.swing.JButton btnTitVenNuevo;
    private javax.swing.JButton btnTitVenSalir;
    private javax.swing.JButton btnTitVendedores;
    private javax.swing.JButton btnTitVentaEliminar;
    private javax.swing.JButton btnTitVentaModificar;
    private javax.swing.JButton btnTitVentaSalir;
    private javax.swing.JButton btnTitVentas;
    private javax.swing.JButton btnVendBuscarCliente;
    private javax.swing.JButton btnVendClienteEliminar;
    private javax.swing.JButton btnVendClienteGuardar;
    private javax.swing.JButton btnVendClienteModificar;
    private javax.swing.JButton btnVendClienteNuevo;
    private javax.swing.JButton btnVendClienteSalir;
    private javax.swing.JButton btnVendClientes;
    private javax.swing.JButton btnVendNuevaVenta;
    private javax.swing.JButton btnVendVentaEliminar;
    private javax.swing.JButton btnVendVentaGuardar;
    private javax.swing.JButton btnVendVentaModificar;
    private javax.swing.JButton btnVendVentaNuevo;
    private javax.swing.JButton btnVendVentaSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblNombreAgencia;
    private javax.swing.JLabel lblNombreAgencia1;
    private javax.swing.JLabel lblTitInmCodAgencia;
    private javax.swing.JLabel lblTitInmNombreAgencia;
    private javax.swing.JLabel lblTitVenCodAgencia;
    private javax.swing.JLabel lblTitVenNombreAgencia;
    private javax.swing.JLabel lblTitVentaCodAgencia;
    private javax.swing.JLabel lblTitVentaNombreAgencia;
    private javax.swing.JLabel lblVendClienteCodAgencia;
    private javax.swing.JLabel lblVendClienteNombreAgencia;
    private javax.swing.JLabel lblVendVentaCodAgencia;
    private javax.swing.JLabel lblVendVentaNombreAgencia;
    private javax.swing.JPanel panelTitInmuebles;
    private javax.swing.JPanel panelTitVendedores;
    private javax.swing.JPanel panelTitVentas;
    private javax.swing.JPanel panelTitular;
    private javax.swing.JPanel panelVendCliente;
    private javax.swing.JPanel panelVendNuevaVenta;
    private javax.swing.JPanel panelVendedor;
    private javax.swing.JTable tablaTitInmueble;
    private javax.swing.JTable tablaTitVendedor;
    private javax.swing.JTable tablaTitVentas;
    private javax.swing.JTable tablaVendCliente;
    private javax.swing.JTable tablaVendVentas;
    private javax.swing.JTextField txtTiVentCorreo;
    private javax.swing.JTextField txtTitInmDireccion;
    private javax.swing.JTextField txtTitInmLicencia;
    private javax.swing.JTextField txtTitInmNumBaños;
    private javax.swing.JTextField txtTitInmNumHab;
    private javax.swing.JTextField txtTitInmPropietario;
    private javax.swing.JTextField txtTitInmSuperficie;
    private javax.swing.JTextField txtTitInmTipoGas;
    private javax.swing.JTextField txtTitInmUbicacion;
    private javax.swing.JTextField txtTitVenApellidos;
    private javax.swing.JTextField txtTitVenDni;
    private javax.swing.JTextField txtTitVenNombre;
    private javax.swing.JTextField txtTitVenTelefono;
    private javax.swing.JTextField txtTitVentaApellidos;
    private javax.swing.JTextField txtTitVentaDni;
    private javax.swing.JTextField txtTitVentaNombre;
    private javax.swing.JTextField txtTitVentaSeñal;
    private javax.swing.JTextField txtTitVentaTelefono;
    private javax.swing.JTextField txtVendClienteApellidos;
    private javax.swing.JTextField txtVendClienteDni;
    private javax.swing.JTextField txtVendClienteNombre;
    private javax.swing.JTextField txtVendClienteTelefono;
    private javax.swing.JTextField txtVendVentaApellidos;
    private javax.swing.JTextField txtVendVentaDni;
    private javax.swing.JTextField txtVendVentaNombre;
    private javax.swing.JTextField txtVendVentaSeñal;
    private javax.swing.JTextField txtVendVentaTelefono;
    // End of variables declaration//GEN-END:variables
}
