package pojo;
// Generated 29-nov-2016 19:53:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String idCliente;
     private String nombre;
     private String apellidos;
     private int telefono;
     private Set ventaInmuebles = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String idCliente, String nombre, String apellidos, int telefono) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.telefono = telefono;
    }
    public Cliente(String idCliente, String nombre, String apellidos, int telefono, Set ventaInmuebles) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.ventaInmuebles = ventaInmuebles;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Set getVentaInmuebles() {
        return this.ventaInmuebles;
    }
    
    public void setVentaInmuebles(Set ventaInmuebles) {
        this.ventaInmuebles = ventaInmuebles;
    }




}


