package pojo;
// Generated 29-nov-2016 19:53:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private String idVendedor;
     private Agencia agencia;
     private String nombre;
     private String apellidos;
     private int titular;
     private Integer telefono;
     private String correo;
     private Set ventaInmuebles = new HashSet(0);

    public Vendedor() {
    }

	
    public Vendedor(String idVendedor, Agencia agencia, String nombre, String apellidos, int titular) {
        this.idVendedor = idVendedor;
        this.agencia = agencia;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.titular = titular;
    }
    public Vendedor(String idVendedor, Agencia agencia, String nombre, String apellidos, int titular, Integer telefono, String correo, Set ventaInmuebles) {
       this.idVendedor = idVendedor;
       this.agencia = agencia;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.titular = titular;
       this.telefono = telefono;
       this.correo = correo;
       this.ventaInmuebles = ventaInmuebles;
    }
   
    public String getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(String idVendedor) {
        this.idVendedor = idVendedor;
    }
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getTitular() {
        return this.titular;
    }
    
    public void setTitular(int titular) {
        this.titular = titular;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getVentaInmuebles() {
        return this.ventaInmuebles;
    }
    
    public void setVentaInmuebles(Set ventaInmuebles) {
        this.ventaInmuebles = ventaInmuebles;
    }




}


