package pojo;
// Generated 29-nov-2016 19:53:01 by Hibernate Tools 4.3.1



/**
 * VentaInmueble generated by hbm2java
 */
public class VentaInmueble  implements java.io.Serializable {


     private VentaInmuebleId id;
     private Cliente cliente;
     private Inmueble inmueble;
     private Vendedor vendedor;
     private float señal;
     private String fecha;

    public VentaInmueble() {
    }

    public VentaInmueble(VentaInmuebleId id, Cliente cliente, Inmueble inmueble, Vendedor vendedor, float señal, String fecha) {
       this.id = id;
       this.cliente = cliente;
       this.inmueble = inmueble;
       this.vendedor = vendedor;
       this.señal = señal;
       this.fecha = fecha;
    }
   
    public VentaInmuebleId getId() {
        return this.id;
    }
    
    public void setId(VentaInmuebleId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public float getSeñal() {
        return this.señal;
    }
    
    public void setSeñal(float señal) {
        this.señal = señal;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


