package pojo;
// Generated 29-nov-2016 19:53:01 by Hibernate Tools 4.3.1



/**
 * VentaInmuebleId generated by hbm2java
 */
public class VentaInmuebleId  implements java.io.Serializable {


     private int idInmueble;
     private String idCliente;
     private String idVendedor;

    public VentaInmuebleId() {
    }

    public VentaInmuebleId(int idInmueble, String idCliente, String idVendedor) {
       this.idInmueble = idInmueble;
       this.idCliente = idCliente;
       this.idVendedor = idVendedor;
    }
   
    public int getIdInmueble() {
        return this.idInmueble;
    }
    
    public void setIdInmueble(int idInmueble) {
        this.idInmueble = idInmueble;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(String idVendedor) {
        this.idVendedor = idVendedor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaInmuebleId) ) return false;
		 VentaInmuebleId castOther = ( VentaInmuebleId ) other; 
         
		 return (this.getIdInmueble()==castOther.getIdInmueble())
 && ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) )
 && ( (this.getIdVendedor()==castOther.getIdVendedor()) || ( this.getIdVendedor()!=null && castOther.getIdVendedor()!=null && this.getIdVendedor().equals(castOther.getIdVendedor()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdInmueble();
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         result = 37 * result + ( getIdVendedor() == null ? 0 : this.getIdVendedor().hashCode() );
         return result;
   }   


}


